name: preload_google_ads
description: "A new Flutter project."
version: 0.0.1
homepage: https://github.com/bhx20/preload_google_ads

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^6.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.plug.preload.preload_google_ads
        pluginClass: PreloadGoogleAdsPlugin


