name: preload_google_ads
description: "Preloading Google Ads in Flutter loads ads in the background for quick display."
version: 0.0.2
homepage: https://github.com/bhx20/Preload-Google-Ads

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.plug.preload
        pluginClass: PreloadGoogleAdsPlugin


